### ISSUE TITLE
ImportError:cannot import name 'DistributedSampler' from 'mmcls.datasets.builder'

### ISSUE THREAD

**Issue by abcsunshine** [open-mmlab/mmfewshot#120]
When I finished the installing and try to run the detection demo, an ImportError occurred.
  
![image](https://user-images.githubusercontent.com/68814215/199638814-6cf78adf-be27-447a-95e8-37bb34650feb.png)

![image](https://user-images.githubusercontent.com/68814215/199638778-aa3b4d57-c66c-4a76-9d18-f6e370cb5698.png)

**Comment by xandril** [comment]
Hi!  mmfewshot doesn't support latest versions of mmcv-full. You should revert it back to 1.4.0

**Comment by YiDanCheung** [comment]
Maybe you installed mmfewshot by this way:`pip install mmfewshot `, and it causes errors like the picture you shown.
And i clone the repository and then install mmfewshot, as stated in the README.
By the way, mmcv-full==1.6.0 ,mmcls==0.25.0, mmdet==2.24.0 can work in my platform（torch1.12.0 ,Cuda11.6）
